# Generated by Django 2.0 on 2018-02-15 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(blank=True, max_length=40)),
                ('location', models.CharField(blank=True, max_length=40)),
                ('degree', models.CharField(blank=True, max_length=40)),
                ('major', models.CharField(blank=True, max_length=40)),
                ('gpa', models.FloatField(blank=True, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=40)),
                ('title', models.CharField(blank=True, max_length=40)),
                ('location', models.CharField(blank=True, max_length=40)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(blank=True, max_length=40)),
                ('Last_name', models.CharField(blank=True, max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='experience',
            name='parent_resume',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resume.Resume'),
        ),
        migrations.AddField(
            model_name='education',
            name='parent_resume',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resume.Resume'),
        ),
    ]
