# Generated by Django 2.0 on 2018-02-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=40)),
                ('location', models.CharField(max_length=40)),
                ('degree', models.CharField(max_length=40)),
                ('major', models.CharField(max_length=40)),
                ('gpa', models.FloatField(max_length=40)),
                ('name', models.FloatField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=40)),
                ('location', models.CharField(max_length=40)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField()),
                ('name', models.FloatField(max_length=40)),
            ],
        ),
    ]
